### ISSUE TITLE
Enhance report with detailed insights

### ISSUE THREAD

**Issue by varchanaiyer** [19Naveen/Knowledge_Representation#11]
Expand the project report to include comprehensive insights derived from data analysis. Document specific patterns, trends, and meaningful findings discovered through the application.

**Comment by SiranjeeviK** [comment]
Hi @varchanaiyer,

Thank you for the suggestion. We appreciate your input and will work on enhancing the project report with detailed insights, including comprehensive analysis of patterns, trends, and key findings.
We expect to have these updates ready within one working day and will keep you informed on our progress.

Best regards,  
Siranjeevi K

**Comment by SiranjeeviK** [comment]
Hi @varchanaiyer,

The issue has been successfully resolved. We've fixed the problem and updated the necessary files. Since we don't have access to a MacBook, we weren't able to test the solution in a Mac environment. However, we have thoroughly tested it in both Windows and Linux environments. The app has also been deployed, and you can review it [here](https://knowledgerepresentation-bitbandits.streamlit.app/) and our improved [guide](https://github.com/19Naveen/Knowledge_Representation?tab=readme-ov-file#how-to-run-the-project).

Please let us know if any further adjustments are needed.

Thank you for your feedback!

Best regards,
@SiranjeeviK
